export const starterKnowledgeBase = [
  {
    condition: "Gastritis",
    summary: "Gastritis is inflammation or irritation of the stomach lining. Common triggers include infection, some pain relievers, alcohol, and stress-related illness.",
    commonSymptoms: ["upper abdominal pain", "nausea", "vomiting", "fullness", "indigestion"],
    riskFactors: ["NSAID use", "alcohol", "H. pylori infection"],
    whenToSeekCare: "Seek urgent care for vomiting blood, black stools, severe pain, fainting, or signs of dehydration.",
    relatedConditions: ["acid reflux", "peptic ulcer", "indigestion"],
    source: "Mayo Clinic",
    sourceURL: "https://www.mayoclinic.org/diseases-conditions/gastritis/symptoms-causes/syc-20355807",
  },
  {
    condition: "Common cold",
    summary: "A common cold is a usually mild viral infection of the nose and throat. Symptoms often improve with rest, fluids, and time.",
    commonSymptoms: ["runny nose", "cough", "sore throat", "sneezing", "mild fever"],
    riskFactors: ["close contact", "low immunity", "seasonal exposure"],
    whenToSeekCare: "Seek medical care for breathing difficulty, high persistent fever, chest pain, or symptoms lasting longer than expected.",
    relatedConditions: ["flu", "COVID-19", "allergic rhinitis"],
    source: "Mayo Clinic",
    sourceURL: "https://www.mayoclinic.org/diseases-conditions/common-cold/symptoms-causes/syc-20351605",
  },
  {
    condition: "Headache",
    summary: "Headaches have many causes, including tension, migraine, dehydration, fever, eye strain, and less commonly serious neurologic conditions.",
    commonSymptoms: ["head pain", "pressure", "light sensitivity", "nausea"],
    riskFactors: ["stress", "lack of sleep", "dehydration", "migraine history"],
    whenToSeekCare: "Urgent care is needed for sudden worst headache, weakness, confusion, fever with stiff neck, head injury, or vision loss.",
    relatedConditions: ["migraine", "tension headache", "sinusitis"],
    source: "NHS",
    sourceURL: "https://www.nhs.uk/conditions/headaches/",
  },
  {
    condition: "Anemia",
    summary: "Anemia means the blood has a reduced ability to carry oxygen, commonly due to low hemoglobin or fewer red blood cells.",
    commonSymptoms: ["fatigue", "weakness", "shortness of breath", "pale skin", "dizziness"],
    riskFactors: ["iron deficiency", "B12 deficiency", "blood loss", "chronic disease"],
    whenToSeekCare: "Discuss low hemoglobin with a clinician, especially with chest pain, fainting, severe breathlessness, pregnancy, or ongoing bleeding.",
    relatedConditions: ["iron deficiency", "B12 deficiency", "chronic kidney disease"],
    source: "WHO",
    sourceURL: "https://www.who.int/health-topics/anaemia",
  },
  {
    condition: "Allergic reaction",
    summary: "Allergic reactions occur when the immune system reacts to a trigger such as food, medicine, insect stings, or environmental exposure.",
    commonSymptoms: ["rash", "itching", "swelling", "hives", "wheezing"],
    riskFactors: ["known allergies", "asthma", "new medicine", "food exposure"],
    whenToSeekCare: "Call emergency services for trouble breathing, throat/tongue swelling, fainting, or rapidly worsening symptoms.",
    relatedConditions: ["anaphylaxis", "urticaria", "contact dermatitis"],
    source: "Mayo Clinic",
    sourceURL: "https://www.mayoclinic.org/diseases-conditions/anaphylaxis/symptoms-causes/syc-20351468",
  },
  {
    condition: "Diabetes",
    summary: "Diabetes is a chronic condition where blood glucose is higher than normal because of insulin production or insulin-use problems.",
    commonSymptoms: ["increased thirst", "frequent urination", "fatigue", "blurred vision"],
    riskFactors: ["family history", "higher body weight", "sedentary lifestyle", "gestational diabetes history"],
    whenToSeekCare: "Seek urgent care for confusion, vomiting, severe weakness, very high glucose, or signs of dehydration.",
    relatedConditions: ["prediabetes", "hypoglycemia", "diabetic ketoacidosis"],
    source: "WHO",
    sourceURL: "https://www.who.int/news-room/fact-sheets/detail/diabetes",
  },
  {
    condition: "Hypertension",
    summary: "Hypertension is persistently elevated blood pressure and often has no symptoms, but it increases risk of heart, kidney, and stroke complications.",
    commonSymptoms: ["often none", "headache", "dizziness"],
    riskFactors: ["age", "salt intake", "family history", "kidney disease", "stress"],
    whenToSeekCare: "Seek urgent care for very high blood pressure with chest pain, shortness of breath, weakness, confusion, or vision changes.",
    relatedConditions: ["heart disease", "stroke", "kidney disease"],
    source: "WHO",
    sourceURL: "https://www.who.int/news-room/fact-sheets/detail/hypertension",
  },
  {
    condition: "Dermatitis",
    summary: "Dermatitis is skin inflammation that can cause redness, itching, dryness, or rash. Causes include irritation, allergy, and eczema.",
    commonSymptoms: ["itching", "rash", "redness", "dry skin", "scaling"],
    riskFactors: ["allergen exposure", "irritants", "eczema history"],
    whenToSeekCare: "Seek care for rapidly spreading rash, fever, severe pain, pus, face swelling, or rash after a new medicine.",
    relatedConditions: ["eczema", "contact dermatitis", "hives"],
    source: "Mayo Clinic",
    sourceURL: "https://www.mayoclinic.org/diseases-conditions/dermatitis-eczema/symptoms-causes/syc-20352380",
  },
];
